name: build (v2)
on:
  push:
  pull_request:

jobs:
  libusb_windows:
    runs-on: windows-2019

    strategy:
      matrix:
        triplet:
          - "x86-windows"
          - "x64-windows"
          - "arm64-windows"

        package:
          - name: "libusb"

    env:
      VCPKG_ROOT: C:\vcpkg

    steps:
      - name: Build ${{ matrix.package.name }}:${{ matrix.triplet }}
        run: vcpkg install ${{ matrix.package.name }}:${{ matrix.triplet }}

      - name: Upload vcpkg artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.package.name }}-${{ github.run_id }}
          path: ${{ env.VCPKG_ROOT }}/installed/

      - name: Upload vcpkg build tree
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.package.name }}-${{ github.run_id }}-buildtree
          path: ${{ env.VCPKG_ROOT }}/buildtrees/${{ matrix.package.name }}/

  libusbdotnet_windows:
    runs-on: windows-2022

    needs: [ libusb_windows ]

    env:
      VCPKG_ROOT: C:\vcpkg

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          name: libusb-${{ github.run_id }}
          path: ${{ env.VCPKG_ROOT }}/installed/

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Build LibUsbDotNet core library
        run: |
          dotnet build stage\LibUsbDotNet\LibUsbDotNet.csproj -c Release -p:TargetFramework=net6.0 --runtime win-x64 --no-self-contained -v n
          dotnet pack stage\LibUsbDotNet\LibUsbDotNet.csproj --no-build -c Release -p:TargetFramework=net6.0 --runtime win-x64 --no-self-contained -v n

      - name: Build LibUsbDotNet solution
        run: dotnet build stage\LibUsbDotNet.sln -c Release

      - name: Upload LibUsbDotNet NuGet package
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: LibUsbDotNet-${{ github.run_id }}
          path: '${{ github.workspace }}/nuget/' 
